language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t evaou/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true evaou/react-test npm test

after_success:
    - docker build -t evaou/docker-client ./client
    - docker build -t evaou/docker-nginx ./nginx
    - docker build -t evaou/docker-server ./server
    - docker build -t evaou/docker-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 
    # Take those images and push them to docker hub
    - docker push evaou/docker-client
    - docker push evaou/docker-nginx
    - docker push evaou/docker-server
    - docker push evaou/docker-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: ap-northeast-1
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-ap-northeast-1-428759872154 
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY